language: emacs-lisp
env:
  matrix:
    # Emacs23 have no ert?
    - EMACS=emacs23
    - EMACS=emacs24
before_install:
  - if [ "$EMACS" = "emacs23" ]; then
        wget "http://git.savannah.gnu.org/cgit/emacs.git/plain/lisp/emacs-lisp/ert.el" &&
        sudo apt-get update &&
        sudo apt-get install emacs23;
    fi
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update &&
        sudo apt-get install emacs24 emacs24-el;
    fi
script:
  - make EMACS=${EMACS} check
